name: keepwarm
on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/10 * * * *"
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Poll the Vercel serverless function to keep it warm
        run: curl https://github-readme-stats-eight-topaz-65.vercel.app
