name: update
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"
jobs:
  keepwarm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci

      - run: npm run update-readme

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Update README.md
